Compatibility with MacOS bash (3.2.57)
mise-plugins/mise-sops pull request #6
Opened 2024-08-15 00:07 UTC by mogest

It turns out `source <(command)` does not work correctly on MacOS Sonoma's bash.

```sh
bash-3.2$ source <(echo "export HELLO=world")
bash-3.2$ echo $HELLO

bash-3.2$
```

Changing `source` to `eval` fixes the problem.  Given all output from the `sops_env` function is escaped, I think this is equally safe.

```sh
bash-3.2$ eval $(echo "export HELLO=world")
bash-3.2$ echo $HELLO
world
bash-3.2$
```

2024-08-15 01:28 UTC, joshbode commented
I gave up on the ancient `bash` that comes with macOS and just installed it with Homebrew (and ensured it was higher up in my `PATH`)

2024-08-15 01:40 UTC, joshbode requested changes
looks good - I think we should add quotes just in case :)

2024-08-15 01:40 UTC, joshbode commented on bin/exec-env
> +eval $(sops_env)
Should we add quotes, e.g.
```suggestion
eval ”$(sops_env)”
```
Shellcheck seems to want them

2024-08-15 01:56 UTC, mogest commented on bin/exec-env
> +eval $(sops_env)
Ah sorry I should have run shellcheck myself first.  I've forced pushed the change to keep your git history tidy :)

2024-08-15 01:57 UTC, mogest commented
> I gave up on the ancient `bash` that comes with macOS and just installed it with Homebrew (and ensured it was higher up in my `PATH`), but definitely I'm for making this more compatible.

This seems very sensible, you have encouraged me to do the same!  Hopefully tho it will help other folks who are still on old bash.

2024-08-15 02:33 UTC, joshbode approved these changes

2024-08-15 02:34 UTC, joshbode commented on bin/exec-env
> +eval $(sops_env)
no worries! that's perfect :)

2024-08-15 02:36 UTC, joshbode commented
thanks for the commit - I hope you find this useful for managing secrets, too - it's been working great for me!

2024-08-15 03:34 UTC, mogest commented
Thanks for maintaining it, we're gonna use it in our team at work for sharing/accessing dev credentials.  Much better than our old solution!

2024-09-02 23:19 UTC, joshbode commented
@jdx could you please take a look at this if you get a chance? Thank you :)

2024-09-03 14:00 UTC, merged